################################################################################
#                                                                              #
#    Noble Shaders                                                             #
#    Copyright (C) 2026  Belmu                                                 #
#                                                                              #
#    This program is free software: you can redistribute it and/or modify      #
#    it under the terms of the GNU General Public License as published by      #
#    the Free Software Foundation, either version 3 of the License, or         #
#    (at your option) any later version.                                       #
#                                                                              #
#    This program is distributed in the hope that it will be useful,           #
#    but WITHOUT ANY WARRANTY; without even the implied warranty of            #
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             #
#    GNU General Public License for more details.                              #
#                                                                              #
#    You should have received a copy of the GNU General Public License         #
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.    #
#                                                                              #
################################################################################

##-----------------# Water #-----------------##

block.1001 = water

##-------------# Light Sources #-------------##

block.1005 = lava magma_block
block.1006 = torch wall_torch lantern:hanging=false fire campfire:lit=true jack_o_lantern

block.1007 = soul_torch soul_wall_torch soul_lantern:hanging=false soul_fire soul_campfire:lit=true \
             copper_torch copper_lantern exposed_copper_lantern weathered_copper_lantern oxidized_copper_lantern \
             waxed_copper_lantern waxed_exposed_copper_lantern waxed_weathered_copper_lantern waxed_oxidized_copper_lantern \
             copper_bulb:lit=true exposed_copper_bulb:lit=true weathered_copper_bulb:lit=true oxidized_copper_bulb:lit=true \
             waxed_copper_bulb:lit=true waxed_exposed_copper_bulb:lit=true waxed_weathered_copper_bulb:lit=true waxed_oxidized_copper_bulb:lit=true

block.1008 = lantern:hanging=true soul_lantern:hanging=true

block.1009 = end_rod sea_lantern glowstone shroomlight ochre_froglight verdant_froglight pearlescent_froglight redstone_lamp:lit=true
block.1010 = nether_portal

##---------------# SSS Misc. #---------------##

block.1011 = \
    cactus vine hay_block kelp kelp_plant bamboo sugar_cane pumpkin_stem melon_stem lily_pad big_dripleaf big_dripleaf_stem honeycomb_block honey_block resin_block \
    clay cobweb sand slime_block ice packed_ice snow_block snow moss_block moss_carpet pale_moss_block pale_moss_carpet azalea flowering_azalea mushroom_stem brown_mushroom_block red_mushroom_block  \
    white_wool orange_wool magenta_wool light_blue_wool yellow_wool lime_wool pink_wool gray_wool light_gray_wool cyan_wool purple_wool blue_wool brown_wool green_wool red_wool black_wool

##----------------# Plants #-----------------##

# Leaves

block.1012 = \
    oak_leaves spruce_leaves birch_leaves jungle_leaves acacia_leaves dark_oak_leaves cherry_leaves mangrove_leaves pale_oak_leaves azalea_leaves flowering_azalea_leaves

# Double plants

block.1013 = sunflower:half=lower lilac:half=lower tall_grass:half=lower large_fern:half=lower rose_bush:half=lower peony:half=lower tall_seagrass:half=lower small_dripleaf:half=lower pitcher_plant:half=lower
block.1014 = sunflower:half=upper lilac:half=upper tall_grass:half=upper large_fern:half=upper rose_bush:half=upper peony:half=upper tall_seagrass:half=upper small_dripleaf:half=upper pitcher_plant:half=upper


# Plants

block.1015 = \
    brown_mushroom red_mushroom \
    short_grass short_dry_grass tall_dry_grass fern bush dead_bush sweet_berry_bush firefly_bush seagrass wheat carrots beetroots potatoes warped_roots crimson_roots nether_sprouts \
    oak_sapling spruce_sapling birch_sapling jungle_sapling acacia_sapling dark_oak_sapling mangrove_propagule cherry_sapling pale_oak_sapling \
    dandelion poppy blue_orchid allium azure_bluet red_tulip orange_tulip white_tulip pink_tulip oxeye_daisy cornflower lily_of_the_valley torchflower cactus_flower \
    closed_eyeblossom open_eyeblossom wither_rose